name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    - name: build
      run: g++ consensify_c.cpp -o consensify_c -lz
    - uses: r-lib/actions/setup-r@v2
      with:
          use-public-rspm: true
    - name: test
      run: |
        cd test
        Rscript test_consensify.R
